INSERT INTO VET VALUES (1, 'James', 'Carter');
INSERT INTO VET VALUES (2, 'Helen', 'Leary');
INSERT INTO VET VALUES (3, 'Linda', 'Douglas');
INSERT INTO VET VALUES (4, 'Rafael', 'Ortega');
INSERT INTO VET VALUES (5, 'Henry', 'Stevens');
INSERT INTO VET VALUES (6, 'Sharon', 'Jenkins');

INSERT INTO SPECIALTIES VALUES (1, 'radiology');
INSERT INTO SPECIALTIES VALUES (2, 'surgery');
INSERT INTO SPECIALTIES VALUES (3, 'dentistry');

INSERT INTO VET_SPECIALTIES VALUES (2, 1);
INSERT INTO VET_SPECIALTIES VALUES (3, 2);
INSERT INTO VET_SPECIALTIES VALUES (3, 3);
INSERT INTO VET_SPECIALTIES VALUES (4, 2);
INSERT INTO VET_SPECIALTIES VALUES (5, 1);