
server:
  port: 8000

spring:
  application:
    name: spring-petvet-customers-service
  datasource:
    url: jdbc:mysql://localhost:3306/petvet
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop


